// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL9hQvu5lxgxz3TEkQOKD340aArqS0wfs',
    appId: '1:232272148396:web:5ecccfd24042b448bcec09',
    messagingSenderId: '232272148396',
    projectId: 'vaseela-app-610c0',
    authDomain: 'vaseela-app-610c0.firebaseapp.com',
    storageBucket: 'vaseela-app-610c0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIXpeymBjFb9XDPSmAMjd8JJ8-1RxUs38',
    appId: '1:232272148396:android:f4f06b473cfa1a17bcec09',
    messagingSenderId: '232272148396',
    projectId: 'vaseela-app-610c0',
    storageBucket: 'vaseela-app-610c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj6YPqCBiGybwLXvW33_fdBiE4RLoqa2o',
    appId: '1:232272148396:ios:f14131be2b16ea35bcec09',
    messagingSenderId: '232272148396',
    projectId: 'vaseela-app-610c0',
    storageBucket: 'vaseela-app-610c0.firebasestorage.app',
    iosBundleId: 'com.example.vaseela',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj6YPqCBiGybwLXvW33_fdBiE4RLoqa2o',
    appId: '1:232272148396:ios:f14131be2b16ea35bcec09',
    messagingSenderId: '232272148396',
    projectId: 'vaseela-app-610c0',
    storageBucket: 'vaseela-app-610c0.firebasestorage.app',
    iosBundleId: 'com.example.vaseela',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL9hQvu5lxgxz3TEkQOKD340aArqS0wfs',
    appId: '1:232272148396:web:ed0d64942c44d020bcec09',
    messagingSenderId: '232272148396',
    projectId: 'vaseela-app-610c0',
    authDomain: 'vaseela-app-610c0.firebaseapp.com',
    storageBucket: 'vaseela-app-610c0.firebasestorage.app',
  );
}
